<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Product extends \App\Entity\Product implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'created_at' => [parent::class, 'created_at', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        "\0".parent::class."\0".'product_category' => [parent::class, 'product_category', null],
        "\0".parent::class."\0".'product_desc' => [parent::class, 'product_desc', null],
        "\0".parent::class."\0".'product_discount' => [parent::class, 'product_discount', null],
        "\0".parent::class."\0".'product_name' => [parent::class, 'product_name', null],
        "\0".parent::class."\0".'product_price' => [parent::class, 'product_price', null],
        "\0".parent::class."\0".'product_qty' => [parent::class, 'product_qty', null],
        "\0".parent::class."\0".'product_status' => [parent::class, 'product_status', null],
        "\0".parent::class."\0".'product_tax_per' => [parent::class, 'product_tax_per', null],
        'created_at' => [parent::class, 'created_at', null],
        'id' => [parent::class, 'id', null],
        'product_category' => [parent::class, 'product_category', null],
        'product_desc' => [parent::class, 'product_desc', null],
        'product_discount' => [parent::class, 'product_discount', null],
        'product_name' => [parent::class, 'product_name', null],
        'product_price' => [parent::class, 'product_price', null],
        'product_qty' => [parent::class, 'product_qty', null],
        'product_status' => [parent::class, 'product_status', null],
        'product_tax_per' => [parent::class, 'product_tax_per', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
