<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Customer extends \App\Entity\Customer implements \Doctrine\ORM\Proxy\InternalProxy
{
    use \Symfony\Component\VarExporter\LazyGhostTrait {
        initializeLazyObject as private;
        setLazyObjectAsInitialized as public __setInitialized;
        isLazyObjectInitialized as private;
        createLazyGhost as private;
        resetLazyObject as private;
    }

    public function __load(): void
    {
        $this->initializeLazyObject();
    }
    

    private const LAZY_OBJECT_PROPERTY_SCOPES = [
        "\0".parent::class."\0".'created_at' => [parent::class, 'created_at', null],
        "\0".parent::class."\0".'customer_address' => [parent::class, 'customer_address', null],
        "\0".parent::class."\0".'customer_email' => [parent::class, 'customer_email', null],
        "\0".parent::class."\0".'customer_mobile' => [parent::class, 'customer_mobile', null],
        "\0".parent::class."\0".'customer_name' => [parent::class, 'customer_name', null],
        "\0".parent::class."\0".'customer_status' => [parent::class, 'customer_status', null],
        "\0".parent::class."\0".'id' => [parent::class, 'id', null],
        'created_at' => [parent::class, 'created_at', null],
        'customer_address' => [parent::class, 'customer_address', null],
        'customer_email' => [parent::class, 'customer_email', null],
        'customer_mobile' => [parent::class, 'customer_mobile', null],
        'customer_name' => [parent::class, 'customer_name', null],
        'customer_status' => [parent::class, 'customer_status', null],
        'id' => [parent::class, 'id', null],
    ];

    public function __isInitialized(): bool
    {
        return isset($this->lazyObjectState) && $this->isLazyObjectInitialized();
    }

    public function __serialize(): array
    {
        $properties = (array) $this;
        unset($properties["\0" . self::class . "\0lazyObjectState"]);

        return $properties;
    }
}
