<?php

namespace ContainerRpruK7b;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored__ServiceLocator_AMhho_E_ThrowableService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.aMhho.e.Throwable' shared service.
     *
     * @return \Throwable
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.aMhho.e": it references interface "Throwable" but no such service exists. Did you create an instantiable class that implements this interface?');
    }
}
